[package]
name = "z_osmf"
version = "0.1.7"
edition = "2021"
authors = ["Billy McGee <william.j.mcgee3@gmail.com>"]
description = "The Rust z/OSMF Client"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/z_osmf"
homepage = "https://crates.io/crates/z_osmf"
repository = "https://github.com/wmcgee3/z_osmf-rs"


[dependencies]
anyhow = "1.0"
bytes = { version = "1.5", features = ["serde"] }
reqwest = { version = "0.11", default-features = false, features = [
    "cookies",
    "json",
] }
serde = { version = "1.0", features = ["derive"] }

z_osmf_core = { version = "0", path = "../z_osmf_core" }
z_osmf_macros = { version = "0", path = "../z_osmf_macros" }


[features]
default = ["datasets", "files", "jobs"]

datasets = []
files = []
jobs = []


[dev-dependencies]
dotenvy = "0.15"
reqwest = { version = "0.11", features = ["rustls-tls"] }
tokio = { version = "1.32", features = ["macros", "rt-multi-thread"] }
